language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

install:
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - composer test

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.5' ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover ./code-coverage/coverage.clover
    fi